# Generated by Django 5.0.7 on 2024-09-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
