# Generated by Django 5.0.7 on 2024-08-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_course_id_customuser_staffs_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staffs',
            new_name='Staff',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='')),
                ('address', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.courses')),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
