# Generated by Django 5.0.7 on 2024-08-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_staffs_staff_student_delete_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
